name: latex_venv
channels:
  - defaults
dependencies:
  - comm=0.1.4
  - cryptography=41.0.3
  - debugpy=1.6.7.post1
  - decorator=5.1.1
  - essential-generators=1.0
  - et-xmlfile=1.1.0
  - executing=1.2.0
  - fonttools=4.39.3
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jedi=0.19.0
  - joblib=1.2.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - kiwisolver=1.4.4
  - lorem-text=2.1
  - matplotlib-inline=0.1.6
  - mysql-connector-python=8.0.33
  - nest-asyncio=1.5.7
  - numpy=1.24.3
  - opencv-python=4.8.1.78
  - openpyxl=3.1.2
  - package-name=0.1
  - packaging=23.1
  - pandas=2.0.1
  - parso=0.8.3
  - pdflatex=0.1.3
  - pdfminer=20191125
  - pdfminer.six=20221105
  - pdfplumber=0.10.2
  - pickleshare=0.7.5
  - Pillow=9.5.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - psutil=5.9.5
  - pure-eval=0.2.2
  - pycparser=2.21
  - pycryptodome=3.18.0
  - Pygments=2.16.1
  - PyMuPDF=1.22.5
  - pyparsing=3.0.9
  - PyPDF2=3.0.1
  - pypdfium2=4.18.0
  - python-dateutil=2.8.2
  - pytz=2023.3
  - pyzmq=25.1.1
  - regex=2023.8.8
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - six=1.16.0
  - stack-data=0.6.2
  - threadpoolctl=3.1.0
  - tornado=6.3.3
  - traitlets=5.9.0
  - tzdata=2023.
  - wcwidth=0.2.6
  - xgboost=1.7.6