#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
mkdir -p "~/results/new_files/"

cp "greedy_from_machine/aaai22.sty" "~/results/aaai22.sty"
cp "greedy_from_machine/bibliography.bib" "~/results/bibliography.bib"
cp "greedy_from_machine/new_files/scenario_visualization.png" "~/results/scenario_visualization.png"

files_dir="greedy_from_machine/files"
results_dir="~/results"
algorithm_variant=0
models_path="greedy_from_machine/classification_models"

python -u greedy_from_machine/new_experiment.py $algorithm_variant $files_dir $results_dir $models_path