(TeX-add-style-hook
 "main"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "letterpaper")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("url" "hyphens") ("algorithm2e" "ruled" "vlined")))
   (TeX-run-style-hooks
    "latex2e"
    "math_commands"
    "article"
    "art10"
    "aaai24"
    "times"
    "helvet"
    "courier"
    "url"
    "graphicx"
    "natbib"
    "caption"
    "algorithm2e"
    "amsthm"
    "multirow"
    "subcaption"
    "mathtools"
    "amssymb")
   (TeX-add-symbols
    '("abs" 1)
    "UrlFont"
    "cN"
    "I"
    "e"
    "V")
   (LaTeX-add-labels
    "sec:intro"
    "sec:background"
    "sec:motiv"
    "sec:motiv-bias"
    "eq:mt"
    "eq:vt"
    "fig:motiv_10001"
    "assumption:stationarity"
    "sec:motiv-sgdm"
    "eq:lr_convert"
    "fig:motiv_sgdm"
    "sec:method"
    "eq:adam_corr"
    "alg:dp_adam"
    "prop:privacy_guarantee"
    "proposition:consistent"
    "prop:bound_fixed"
    "prop:bound_martingale"
    "sec:exp"
    "tab:res_multi_eps"
    "fig:compare_dp2_snli_only"
    "eval:empirical-effect-correction"
    "tab:exp2"
    "fig:mt_vt_hist"
    "fig:exp3_4"
    "apdix:exp_setup"
    "apdix:consistent"
    "apdix:bound"
    "lemma:zk2_sub_exponential"
    "appendix:bound_fixed"
    "appendix:bound_martingale"
    "appendix:num-analysis"
    "tab:num_bound_fixed_grad"
    "tab:num_bound"
    "tab:empirical_bound"
    "apdix:more_res"
    "fig:res_multi_eps"
    "fig:exp_rel_sgdm_more"
    "apdix:additional_exp"
    "fig:exp1"
    "fig:additional_exp"
    "apdix:compare_dp2"
    "fig:compare_dp2_cifar_only"
    "apdix:privacy_proof"
    "apdix:convergence_analysis"
    "assmption:f_bounded_below"
    "assmption:bounded_stochastic_grad"
    "lemma:gaussian_concentration_on_z"
    "lemma:union_bound_on_v"
    "assmption:f_smooth")
   (LaTeX-add-environments
    "assumption"
    "proposition"
    "theorem"
    "lemma"
    "corollary")
   (LaTeX-add-bibliographies))
 :latex)

