#!/usr/bin/env bash
set -ex


permutation=51500 #permutation_number. Change it in order to generate different paper.
batch_number=1030 #batch number of the current machine. Use it in order to split tasks to different machines


documents_pat="~/results/docs/" 
mkdir -p $documents_pat

document_dir="~/results/docs/$batch_number/" #all documents from the same machine will be written to here
mkdir -p $document_dir

#coppying style elements to this directory
cp style_tex/bibliography.bib $documents_pat
cp style_tex/aaai22.sty $documents_pat
cp style_tex/aaai22.bst $documents_pat
cp style_tex/aaai22.bib $documents_pat
cp style_tex/visualization.png $documents_pat
bibpat="/code/style_tex/bibliography.bib" #path to bibliography file

#creating loggs
mkdir -p "~/results/errors_occured_during_generations"
errs_to="~/results/errors_occured_during_generations/$batch_number"
mkdir -p "~/results/files_to_fix"
fixing_to="~/results/files_to_fix/$batch_number"

#excels of feature extraction will be written to here
mkdir -p ~/results/excels_of_data
excelpat="~/results/excels_of_data/$batch_number.csv"

#pickle files of results from processes will be written to here.
mkdir -p "~/results/analysis_dictionaries/$batch_number"
analysis_to="~/results/analysis_dictionaries/$batch_number/" #pickle of result of mapping tex to pdf process
mkdir -p "~/results/features_dictionaries/$batch_number"
features_to="~/results/features_dictionaries/$batch_number/" #pickle of results of feature extraction process
  
python -u generation_of_file.py ${permutation} ${batch_number} ${document_dir} ${bibpat} ${errs_to} ${fixing_to} ${excelpat} ${features_to} ${analysis_to}